---
title: "Barune_TileHeatmap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r cars}
library(tidyverse)
library(rvest)
library(lubridate)
library(knitr)
library(plyr)
library(dplyr)
library(ggplot2)
```

## Wrangle Data

```{r pressure, echo=FALSE}
# Read individual country CSVs, add column with country name, and join into "all_countries" dataframe

Afghanistan <- read.csv("Afghanistan.csv")
Afghanistan <- data.frame(append(Afghanistan, c(Country='Afghanistan'), after=0))
all_countries <- Afghanistan

Albania <- read.csv("Albania.csv")
Albania <- data.frame(append(Albania, c(Country='Albania'), after=0))
all_countries <- bind_rows(all_countries, Albania)

Algeria <- read.csv("Algeria.csv")
Algeria <- data.frame(append(Algeria, c(Country='Algeria'), after=0))
all_countries <- bind_rows(all_countries, Algeria)

Argentina <- read.csv("Argentina.csv")
Argentina <- data.frame(append(Argentina, c(Country='Argentina'), after=0))
all_countries <- bind_rows(all_countries, Argentina)

Australia <- read.csv("Australia.csv")
Australia <- data.frame(append(Australia, c(Country='Australia'), after=0))
all_countries <- bind_rows(all_countries, Australia)

Austria <- read.csv("Austria.csv")
Austria <- data.frame(append(Austria, c(Country='Austria'), after=0))
all_countries <- bind_rows(all_countries, Austria)

Azerbaijan <- read.csv("Azerbaijan.csv")
Azerbaijan <- data.frame(append(Azerbaijan, c(Country='Azerbaijan'), after=0))
all_countries <- bind_rows(all_countries, Azerbaijan)

Bahrain <- read.csv("Bahrain.csv")
Bahrain <- data.frame(append(Bahrain, c(Country='Bahrain'), after=0))
all_countries <- bind_rows(all_countries, Bahrain)

Bangladesh <- read.csv("Bangladesh.csv")
Bangladesh <- data.frame(append(Bangladesh, c(Country='Bangladesh'), after=0))
all_countries <- bind_rows(all_countries, Bangladesh)

Beglium <- read.csv("Belgium.csv")
Beglium <- data.frame(append(Beglium, c(Country='Beglium'), after=0))
all_countries <- bind_rows(all_countries, Beglium)

Belize <- read.csv("Belize.csv")
Belize <- data.frame(append(Belize, c(Country='Belize'), after=0))
all_countries <- bind_rows(all_countries, Belize)

Bhutan <- read.csv("Bhutan.csv")
Bhutan <- data.frame(append(Bhutan, c(Country='Bhutan'), after=0))
all_countries <- bind_rows(all_countries, Bhutan)

Bosnia_and_Herzegovina <- read.csv("Bosnia and Herzegovina.csv")
Bosnia_and_Herzegovina <- data.frame(append(Bosnia_and_Herzegovina, c(Country='Bosnia and Herzegovina'), after=0))
all_countries <- bind_rows(all_countries, Bosnia_and_Herzegovina)

Botswana <- read.csv("Botswana.csv")
Botswana <- data.frame(append(Botswana, c(Country='Botswana'), after=0))
all_countries <- bind_rows(all_countries, Botswana)

Brazil <- read.csv("Brazil.csv")
Brazil <- data.frame(append(Brazil, c(Country='Brazil'), after=0))
all_countries <- bind_rows(all_countries, Brazil)

Bulgaria <- read.csv("Bulgaria.csv")
Bulgaria <- data.frame(append(Bulgaria, c(Country='Bulgaria'), after=0))
all_countries <- bind_rows(all_countries, Bulgaria)

Burkina_Faso <- read.csv("Burkina Faso.csv")
Burkina_Faso <- data.frame(append(Burkina_Faso, c(Country='Burkina Faso'), after=0))
all_countries <- bind_rows(all_countries, Burkina_Faso)

Cabo_Verde <- read.csv("Cabo Verde.csv")
Cabo_Verde <- data.frame(append(Cabo_Verde, c(Country='Cabo Verde'), after=0))
all_countries <- bind_rows(all_countries, Cabo_Verde)

Canada <- read.csv("Canada.csv")
Canada <- data.frame(append(Canada, c(Country='Canada'), after=0))
all_countries <- bind_rows(all_countries, Canada)

CAR <- read.csv("Central African Republic.csv")
CAR <- data.frame(append(CAR, c(Country='Central African Republic'), after=0))
all_countries <- bind_rows(all_countries, CAR)

Chad <- read.csv("Chad.csv")
Chad <- data.frame(append(Chad, c(Country='Chad'), after=0))
all_countries <- bind_rows(all_countries, Chad)

Chile <- read.csv("Chile.csv")
Chile <- data.frame(append(Chile, c(Country='Chile'), after=0))
all_countries <- bind_rows(all_countries, Chile)

China <- read.csv("China.csv")
China <- data.frame(append(China, c(Country='China'), after=0))
all_countries <- bind_rows(all_countries, China)

Colombia <- read.csv("Colombia.csv")
Colombia <- data.frame(append(Colombia, c(Country='Colombia'), after=0))
all_countries <- bind_rows(all_countries, Colombia)

Costa_Rica <- read.csv("Costa Rica.csv")
Costa_Rica <- data.frame(append(Costa_Rica, c(Country='Costa Rica'), after=0))
all_countries <- bind_rows(all_countries, Costa_Rica)

Croatia <- read.csv("Croatia.csv")
Croatia <- data.frame(append(Croatia, c(Country='Croatia'), after=0))
all_countries <- bind_rows(all_countries, Croatia)

Cuba <- read.csv("Cuba.csv")
Cuba <- data.frame(append(Cuba, c(Country='Cuba'), after=0))
all_countries <- bind_rows(all_countries, Cuba)

Cyprus <- read.csv("Cyprus.csv")
Cyprus <- data.frame(append(Cyprus, c(Country='Cyprus'), after=0))
all_countries <- bind_rows(all_countries, Cyprus)

Czech_Republic <- read.csv("Czech Republic.csv")
Czech_Republic <- data.frame(append(Czech_Republic, c(Country='Czech Republic'), after=0))
all_countries <- bind_rows(all_countries, Czech_Republic)

Denmark <- read.csv("Denmark.csv")
Denmark <- data.frame(append(Denmark, c(Country='Denmark'), after=0))
all_countries <- bind_rows(all_countries, Denmark)

Djibouti <- read.csv("Djibouti.csv")
Djibouti <- data.frame(append(Djibouti, c(Country='Djibouti'), after=0))
all_countries <- bind_rows(all_countries, Djibouti)

Dominican_Republic <- read.csv("Dominican Republic.csv")
Dominican_Republic <- data.frame(append(Dominican_Republic, c(Country='Dominican Republic'), after=0))
all_countries <- bind_rows(all_countries, Dominican_Republic)

Ecuador <- read.csv("Ecuador.csv")
Ecuador <- data.frame(append(Ecuador, c(Country='Ecuador'), after=0))
all_countries <- bind_rows(all_countries, Ecuador)

El_Salvador <- read.csv("El Salvador.csv")
El_Salvador <- data.frame(append(El_Salvador, c(Country='El Salvador'), after=0))
all_countries <- bind_rows(all_countries, El_Salvador)

Equatorial <- read.csv("Equatorial Guinea.csv")
Equatorial <- data.frame(append(Equatorial, c(Country='Equatorial Guinea'), after=0))
all_countries <- bind_rows(all_countries, Equatorial)

Estonia <- read.csv("Estonia.csv")
Estonia <- data.frame(append(Estonia, c(Country='Estonia'), after=0))
all_countries <- bind_rows(all_countries, Estonia)

Eswatini <- read.csv("Eswatini.csv")
Eswatini <- data.frame(append(Eswatini, c(Country='Eswatini'), after=0))
all_countries <- bind_rows(all_countries, Eswatini)

Ethiopia <- read.csv("Ethiopia.csv")
Ethiopia <- data.frame(append(Ethiopia, c(Country='Ethiopia'), after=0))
all_countries <- bind_rows(all_countries, Ethiopia)

Ethiopia <- read.csv("Ethiopia.csv")
Ethiopia <- data.frame(append(Ethiopia, c(Country='Ethiopia'), after=0))
all_countries <- bind_rows(all_countries, Ethiopia)

Finland <- read.csv("Finland.csv")
Finland <- data.frame(append(Finland, c(Country='Finland'), after=0))
all_countries <- bind_rows(all_countries, Finland)

France <- read.csv("France.csv")
France <- data.frame(append(France, c(Country='France'), after=0))
all_countries <- bind_rows(all_countries, France)

French_P <- read.csv("French Polynesia.csv")
French_P <- data.frame(append(French_P, c(Country='French Polynesia'), after=0))
all_countries <- bind_rows(all_countries, French_P)

Gabon <- read.csv("Gabon.csv")
Gabon <- data.frame(append(Gabon, c(Country='Gabon'), after=0))
all_countries <- bind_rows(all_countries, Gabon)

Gambia <- read.csv("Gambia.csv")
Gambia <- data.frame(append(Gambia, c(Country='Gambia'), after=0))
all_countries <- bind_rows(all_countries, Gambia)

Germany <- read.csv("Germany.csv")
Germany <- data.frame(append(Germany, c(Country='Germany'), after=0))
all_countries <- bind_rows(all_countries, Germany)

Ghana <- read.csv("Ghana.csv")
Ghana <- data.frame(append(Ghana, c(Country='Ghana'), after=0))
all_countries <- bind_rows(all_countries, Ghana)

Greece <- read.csv("Greece.csv")
Greece <- data.frame(append(Greece, c(Country='Greece'), after=0))
all_countries <- bind_rows(all_countries, Greece)

Guatemala <- read.csv("Guatemala.csv")
Guatemala <- data.frame(append(Guatemala, c(Country='Guatemala'), after=0))
all_countries <- bind_rows(all_countries, Guatemala)

Guernsey <- read.csv("Guernsey.csv")
Guernsey <- data.frame(append(Guernsey, c(Country='Guernsey'), after=0))
all_countries <- bind_rows(all_countries, Guernsey)

Guinea <- read.csv("Guinea.csv")
Guinea <- data.frame(append(Guinea, c(Country='Guinea'), after=0))
all_countries <- bind_rows(all_countries, Guinea)

Guyana <- read.csv("Guyana.csv")
Guyana <- data.frame(append(Guyana, c(Country='Guyana'), after=0))
all_countries <- bind_rows(all_countries, Guyana)

Haiti <- read.csv("Haiti.csv")
Haiti <- data.frame(append(Haiti, c(Country='Haiti'), after=0))
all_countries <- bind_rows(all_countries, Haiti)

Honduras <- read.csv("Honduras.csv")
Honduras <- data.frame(append(Honduras, c(Country='Honduras'), after=0))
all_countries <- bind_rows(all_countries, Honduras)

Hong <- read.csv("Hong Kong.csv")
Hong <- data.frame(append(Hong, c(Country='Hong Kong'), after=0))
all_countries <- bind_rows(all_countries, Hong)

Iceland <- read.csv("Iceland.csv")
Iceland <- data.frame(append(Iceland, c(Country='Iceland'), after=0))
all_countries <- bind_rows(all_countries, Iceland)

India <- read.csv("India.csv")
India <- data.frame(append(India, c(Country='India'), after=0))
all_countries <- bind_rows(all_countries, India)

Indonesia <- read.csv("Indonesia.csv")
Indonesia <- data.frame(append(Indonesia, c(Country='India'), after=0))
all_countries <- bind_rows(all_countries, Indonesia)

Iran <- read.csv("Iran.csv")
Iran <- data.frame(append(Iran, c(Country='Iran'), after=0))
all_countries <- bind_rows(all_countries, Iran)

Iraq <- read.csv("Iraq.csv")
Iraq <- data.frame(append(Iraq, c(Country='Iraq'), after=0))
all_countries <- bind_rows(all_countries, Iraq)

Israel <- read.csv("Israel.csv")
Israel <- data.frame(append(Israel, c(Country='Israel'), after=0))
all_countries <- bind_rows(all_countries, Israel)

Italy <- read.csv("Italy.csv")
Italy <- data.frame(append(Italy, c(Country='Italy'), after=0))
all_countries <- bind_rows(all_countries, Italy)

Jamaica <- read.csv("Jamaica.csv")
Jamaica <- data.frame(append(Jamaica, c(Country='Jamaica'), after=0))
all_countries <- bind_rows(all_countries, Jamaica)

Japan <- read.csv("Japan.csv")
Japan <- data.frame(append(Japan, c(Country='Japan'), after=0))
all_countries <- bind_rows(all_countries, Japan)

Jersey <- read.csv("Jersey.csv")
Jersey <- data.frame(append(Jersey, c(Country='Jersey'), after=0))
all_countries <- bind_rows(all_countries, Jersey)

Kazakhstan <- read.csv("Kazakhstan.csv")
Kazakhstan <- data.frame(append(Kazakhstan, c(Country='Kazakhstan'), after=0))
all_countries <- bind_rows(all_countries, Kazakhstan)

Kenya <- read.csv("Kenya.csv")
Kenya <- data.frame(append(Kenya, c(Country='Kenya'), after=0))
all_countries <- bind_rows(all_countries, Kenya)

Kyrgyzstan <- read.csv("Kyrgyzstan.csv")
Kyrgyzstan <- data.frame(append(Kyrgyzstan, c(Country='Kyrgyzstan'), after=0))
all_countries <- bind_rows(all_countries, Kyrgyzstan)

Latvia <- read.csv("Latvia.csv")
Latvia <- data.frame(append(Latvia, c(Country='Latvia'), after=0))
all_countries <- bind_rows(all_countries, Latvia)

Lebanon <- read.csv("Lebanon.csv")
Lebanon <- data.frame(append(Lebanon, c(Country='Lebanon'), after=0))
all_countries <- bind_rows(all_countries, Lebanon)

Liberia <- read.csv("Liberia.csv")
Liberia <- data.frame(append(Liberia, c(Country='Liberia'), after=0))
all_countries <- bind_rows(all_countries, Liberia)

Lithuania <- read.csv("Lithuania.csv")
Lithuania <- data.frame(append(Lithuania, c(Country='Lithuania'), after=0))
all_countries <- bind_rows(all_countries, Lithuania)

Luxembourg <- read.csv("Luxembourg.csv")
Luxembourg <- data.frame(append(Luxembourg, c(Country='Luxembourg'), after=0))
all_countries <- bind_rows(all_countries, Luxembourg)

Malawi <- read.csv("Malawi.csv")
Malawi <- data.frame(append(Malawi, c(Country='Malawi'), after=0))
all_countries <- bind_rows(all_countries, Malawi)

Maldives <- read.csv("Maldives.csv")
Maldives <- data.frame(append(Maldives, c(Country='Maldives'), after=0))
all_countries <- bind_rows(all_countries, Maldives)

Mali <- read.csv("Mali.csv")
Mali <- data.frame(append(Mali, c(Country='Mali'), after=0))
all_countries <- bind_rows(all_countries, Mali)

Malta <- read.csv("Malta.csv")
Malta <- data.frame(append(Malta, c(Country='Malta'), after=0))
all_countries <- bind_rows(all_countries, Malta)

Mexico <- read.csv("Mexico.csv")
Mexico <- data.frame(append(Mexico, c(Country='Mexico'), after=0))
all_countries <- bind_rows(all_countries, Mexico)

Moldova <- read.csv("Moldova.csv")
Moldova <- data.frame(append(Moldova, c(Country='Moldova'), after=0))
all_countries <- bind_rows(all_countries, Moldova)

Mongolia <- read.csv("Mongolia.csv")
Mongolia <- data.frame(append(Mongolia, c(Country='Mongolia'), after=0))
all_countries <- bind_rows(all_countries, Mongolia)

Montenegro <- read.csv("Montenegro.csv")
Montenegro <- data.frame(append(Montenegro, c(Country='Montenegro'), after=0))
all_countries <- bind_rows(all_countries, Montenegro)

Morocco <- read.csv("Morocco.csv")
Morocco <- data.frame(append(Morocco, c(Country='Morocco'), after=0))
all_countries <- bind_rows(all_countries, Morocco)

Mozambique <- read.csv("Mozambique.csv")
Mozambique <- data.frame(append(Mozambique, c(Country='Mozambique'), after=0))
all_countries <- bind_rows(all_countries, Mozambique)

Myanmar <- read.csv("Myanmar.csv")
Myanmar <- data.frame(append(Myanmar, c(Country='Myanmar'), after=0))
all_countries <- bind_rows(all_countries, Myanmar)

Nepal <- read.csv("Nepal.csv")
Nepal <- data.frame(append(Nepal, c(Country='Nepal'), after=0))
all_countries <- bind_rows(all_countries, Nepal)

Netherlands <- read.csv("Netherlands.csv")
Netherlands <- data.frame(append(Netherlands, c(Country='Netherlands'), after=0))
all_countries <- bind_rows(all_countries, Netherlands)

New_Z <- read.csv("New Zealand.csv")
New_Z <- data.frame(append(New_Z, c(Country='New Zealand'), after=0))
all_countries <- bind_rows(all_countries, New_Z)

Nigeria <- read.csv("Nigeria.csv")
Nigeria <- data.frame(append(Nigeria, c(Country='Nigeria'), after=0))
all_countries <- bind_rows(all_countries, Nigeria)

North_Mac <- read.csv("North Macedonia.csv")
North_Mac <- data.frame(append(North_Mac, c(Country='North Macedonia'), after=0))
all_countries <- bind_rows(all_countries, North_Mac)

Norway <- read.csv("Norway.csv")
Norway <- data.frame(append(Norway, c(Country='Norway'), after=0))
all_countries <- bind_rows(all_countries, Norway)

Pakistan <- read.csv("Pakistan.csv")
Pakistan <- data.frame(append(Pakistan, c(Country='Pakistan'), after=0))
all_countries <- bind_rows(all_countries, Pakistan)

Palestine <- read.csv("Palestine.csv")
Palestine <- data.frame(append(Palestine, c(Country='Palestine'), after=0))
all_countries <- bind_rows(all_countries, Palestine)

Panama <- read.csv("Panama.csv")
Panama <- data.frame(append(Panama, c(Country='Panama'), after=0))
all_countries <- bind_rows(all_countries, Panama)

Paraguay <- read.csv("Paraguay.csv")
Paraguay <- data.frame(append(Paraguay, c(Country='Paraguay'), after=0))
all_countries <- bind_rows(all_countries, Paraguay)

Peru <- read.csv("Peru.csv")
Peru <- data.frame(append(Peru, c(Country='Peru'), after=0))
all_countries <- bind_rows(all_countries, Peru)

Peru <- read.csv("Peru.csv")
Peru <- data.frame(append(Peru, c(Country='Peru'), after=0))
all_countries <- bind_rows(all_countries, Peru)

Philippines <- read.csv("Philippines.csv")
Philippines <- data.frame(append(Philippines, c(Country='Philippines'), after=0))
all_countries <- bind_rows(all_countries, Philippines)

Portugal <- read.csv("Portugal.csv")
Portugal <- data.frame(append(Portugal, c(Country='Portugal'), after=0))
all_countries <- bind_rows(all_countries, Portugal)

Qatar <- read.csv("Qatar.csv")
Qatar <- data.frame(append(Qatar, c(Country='Qatar'), after=0))
all_countries <- bind_rows(all_countries, Qatar)

Ireland <- read.csv("Republic of Ireland.csv")
Ireland <- data.frame(append(Ireland, c(Country='Republic of Ireland'), after=0))
all_countries <- bind_rows(all_countries, Ireland)

Romania <- read.csv("Romania.csv")
Romania <- data.frame(append(Romania, c(Country='Romania'), after=0))
all_countries <- bind_rows(all_countries, Romania)

Rwanda <- read.csv("Rwanda.csv")
Rwanda <- data.frame(append(Rwanda, c(Country='Rwanda'), after=0))
all_countries <- bind_rows(all_countries, Rwanda)

Saudi <- read.csv("Saudi Arabia.csv")
Saudi <- data.frame(append(Saudi, c(Country='Saudi Arabia'), after=0))
all_countries <- bind_rows(all_countries, Saudi)

Senegal <- read.csv("Senegal.csv")
Senegal <- data.frame(append(Senegal, c(Country='Senegal'), after=0))
all_countries <- bind_rows(all_countries, Senegal)

Sierra <- read.csv("Sierra Leone.csv")
Sierra <- data.frame(append(Sierra, c(Country='Sierra Leone'), after=0))
all_countries <- bind_rows(all_countries, Sierra)

Singapore <- read.csv("Singapore.csv")
Singapore <- data.frame(append(Singapore, c(Country='Singapore'), after=0))
all_countries <- bind_rows(all_countries, Singapore)

Slovakia <- read.csv("Slovakia.csv")
Slovakia <- data.frame(append(Slovakia, c(Country='Slovakia'), after=0))
all_countries <- bind_rows(all_countries, Slovakia)

Slovenia <- read.csv("Slovenia.csv")
Slovenia <- data.frame(append(Slovenia, c(Country='Slovenia'), after=0))
all_countries <- bind_rows(all_countries, Slovenia)

Somalia <- read.csv("Somalia.csv")
Somalia <- data.frame(append(Somalia, c(Country='Somalia'), after=0))
all_countries <- bind_rows(all_countries, Somalia)

South_Africa <- read.csv("South Africa.csv")
South_Africa <- data.frame(append(South_Africa, c(Country='South Africa'), after=0))
all_countries <- bind_rows(all_countries, South_Africa)

South_Korea <- read.csv("South Korea.csv")
South_Korea <- data.frame(append(South_Korea, c(Country='South Korea'), after=0))
all_countries <- bind_rows(all_countries, South_Korea)

South_Sudan <- read.csv("South Sudan.csv")
South_Sudan <- data.frame(append(South_Sudan, c(Country='South Sudan'), after=0))
all_countries <- bind_rows(all_countries, South_Sudan)

Spain <- read.csv("Spain.csv")
Spain <- data.frame(append(Spain, c(Country='Spain'), after=0))
all_countries <- bind_rows(all_countries, Spain)

Sweden <- read.csv("Sweden.csv")
Sweden <- data.frame(append(Sweden, c(Country='Sweden'), after=0))
all_countries <- bind_rows(all_countries, Sweden)

Switzerland <- read.csv("Switzerland.csv")
Switzerland <- data.frame(append(Switzerland, c(Country='Switzerland'), after=0))
all_countries <- bind_rows(all_countries, Switzerland)

Taiwan <- read.csv("Taiwan.csv")
Taiwan <- data.frame(append(Taiwan, c(Country='Taiwan'), after=0))
all_countries <- bind_rows(all_countries, Taiwan)

Thailand <- read.csv("Thailand.csv")
Thailand <- data.frame(append(Thailand, c(Country='Thailand'), after=0))
all_countries <- bind_rows(all_countries, Thailand)

Tunisia <- read.csv("Tunisia.csv")
Tunisia <- data.frame(append(Tunisia, c(Country='Tunisia'), after=0))
all_countries <- bind_rows(all_countries, Tunisia)

Turkey <- read.csv("Turkey.csv")
Turkey <- data.frame(append(Turkey, c(Country='Turkey'), after=0))
all_countries <- bind_rows(all_countries, Turkey)

Uganda <- read.csv("Uganda.csv")
Uganda <- data.frame(append(Uganda, c(Country='Uganda'), after=0))
all_countries <- bind_rows(all_countries, Uganda)

Ukraine <- read.csv("Ukraine.csv")
Ukraine <- data.frame(append(Ukraine, c(Country='Ukraine'), after=0))
all_countries <- bind_rows(all_countries, Ukraine)

USA <- read.csv("USA.csv")
USA <- data.frame(append(USA, c(Country='USA'), after=0))
all_countries <- bind_rows(all_countries, USA)

Venezuela <- read.csv("Venezuela.csv")
Venezuela <- data.frame(append(Venezuela, c(Country='Venezuela'), after=0))
all_countries <- bind_rows(all_countries, Venezuela)

Vietnam <- read.csv("Vietnam.csv")
Vietnam <- data.frame(append(Vietnam, c(Country='Vietnam'), after=0))
all_countries <- bind_rows(all_countries, Vietnam)

Yemen <- read.csv("Yemen.csv")
Yemen <- data.frame(append(Yemen, c(Country='Yemen'), after=0))
all_countries <- bind_rows(all_countries, Yemen)



# Date Formatting
all_countries$Date = parse_date_time(all_countries$Date, orders = "dm")

```

```{r fig.width=7, fig.height=15}

#Add Month Column
all_countries$Month <- month(all_countries$Date)

#Summarize all country data by month (not enough data across countries to do day by day tile plot)
month_org = all_countries %>% group_by(Country, Month) %>% summarise_each(funs(mean))

# Add Sex Ratio Column (M:F)
SR_country <- month_org %>% mutate(sex_ratio = Male/Female)


library(RColorBrewer)
library(scales)
# Created tile plot with each box representing a state and year with a gradient filling which represents the square root of the rate
tileplot <- SR_country %>% ggplot(aes(Month, Country,  fill = sex_ratio)) +
        geom_tile(color = "grey50") +
        scale_x_continuous(name="Month", limits=c(2, 11)) +
        scale_fill_gradientn(colors = brewer.pal(9, "Blues"), trans = "sqrt") +
        theme_minimal() +  theme(panel.grid = element_blank()) +
        ggtitle("COVID-19 Case Sex Ratio by Country from Jan '20 to Nov '20") + 
        ylab("Country") + 
        xlab("Month")

print(tileplot)
```
all_countries$Month <- parse_date_time(all_countries$Month, orders = "m")

  format(as.Date(all_countries$Date), "%m")
  
  #Reformat "Month" Column
month_org$Month <- parse_date_time(month_org$Month, orders = "m")