---
title: "MN_CovariateScatterplots"
author: "Michelle"
date: "12/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(rvest)
library(purrr)
library(dplyr)
library(ggplot2)
library(maps)
library(tidyr)


# Upload the Census data on median income and filter to only include State names and their median income in 2018.Rename.
medinc <- read.csv("median_income.csv")
medinc <- medinc %>%
  group_by(State) %>%
  select("State", "X2018") %>%
  rename("Median Income" = "X2018")

# Remove the first row. 
medinc <- medinc[-c(1), ]
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Upload
## Percent living in poverty
pov <- read.csv("Census_percentage ppl in poverty by state using 2-3 year averages.csv")


#Select and rename columns
pov <- pov %>%
  select("Table.with.row.headings.in.column.A.and.column.headings.in.rows.5.to.10.", "X.4") %>%
  rename("State" = "Table.with.row.headings.in.column.A.and.column.headings.in.rows.5.to.10.") %>%
  rename("Percent Pov" = "X.4")

#Drop unnecessary rows.
pov <- pov[-c(1:8, 10, 21, 32, 43, 54, 66:73), ] 

#Rename States
medinc$State <- as.character(medinc$State)
pov$State <- as.character(pov$State)

pov$State[grepl("Alabama...................", pov$State)] <- "Alabama"
pov$State[grepl("Alaska.....................", pov$State)] <- "Alaska"
pov$State[grepl("Arizona....................", pov$State)] <- "Arizona"
pov$State[grepl("Arkansas.................", pov$State)] <- "Arkansas"
pov$State[grepl("California..................", pov$State)] <- "California"
pov$State[grepl("Colorado..................", pov$State)] <- "Colorado"
pov$State[grepl("Connecticut..............", pov$State)] <- "Connecticut"
pov$State[grepl("Delaware..................", pov$State)] <- "Delaware"
pov$State[grepl("District of Columbia….", pov$State)] <- "District of Columbia"
pov$State[grepl("Florida.....................", pov$State)] <-"Florida"
pov$State[grepl("Georgia.....................", pov$State)] <-"Georgia"
pov$State[grepl("Hawaii......................", pov$State)] <-"Hawaii"
pov$State[grepl("Idaho........................", pov$State)] <-"Idaho"
pov$State[grepl("Illinois.......................", pov$State)] <-"Illinois"
pov$State[grepl("Indiana.....................", pov$State)] <-"Indiana"
pov$State[grepl("Iowa..........................", pov$State)] <-"Iowa"
pov$State[grepl("Kansas....................", pov$State)] <-"Kansas"
pov$State[grepl("Kentucky..................", pov$State)] <-"Kentucky"
pov$State[grepl("Louisiana..................", pov$State)] <-"Louisiana"
pov$State[grepl("Maine.......................", pov$State)] <-"Maine"
pov$State[grepl("Maryland...................", pov$State)] <-"Maryland"
pov$State[grepl("Massachusetts.........", pov$State)] <-"Massachusetts"
pov$State[grepl("Michigan...................", pov$State)] <-"Michigan"
pov$State[grepl("Minnesota.................", pov$State)] <-"Minnesota"
pov$State[grepl("Mississippi...............", pov$State)] <-"Mississippi"
pov$State[grepl("Missouri...................", pov$State)] <-"Missouri"
pov$State[grepl("Montana...................", pov$State)] <-"Montana"
pov$State[grepl("Nebraska..................", pov$State)] <-"Nebraska"
pov$State[grepl("Nevada......................", pov$State)] <-"Nevada"
pov$State[grepl("New Hampshire.........", pov$State)] <-"New Hampshire"
pov$State[grepl("New Jersey...............", pov$State)] <-"New Jersey"
pov$State[grepl("New Mexico...............", pov$State)] <-"New Mexico"
pov$State[grepl("New York..................", pov$State)] <-"New York"
pov$State[grepl("North Carolina...........", pov$State)] <-"North Carolina"
pov$State[grepl("North Dakota.............", pov$State)] <-"North Dakota"
pov$State[grepl("Ohio.........................", pov$State)] <-"Ohio"
pov$State[grepl("Oklahoma.................", pov$State)] <-"Oklahoma"
pov$State[grepl("Oregon.....................", pov$State)] <-"Oregon"
pov$State[grepl("Pennsylvania.............", pov$State)] <-"Pennsylvania"
pov$State[grepl("Rhode Island.............", pov$State)] <-"Rhode Island"
pov$State[grepl("South Carolina..........", pov$State)] <- "South Carolina"
pov$State[grepl("South Dakota............", pov$State)] <-"South Dakota"
pov$State[grepl("Tennessee................", pov$State)] <-"Tennessee"
pov$State[grepl("Texas.......................", pov$State)] <-"Texas"
pov$State[grepl("Utah.........................", pov$State)] <-"Utah"
pov$State[grepl("Vermont...................", pov$State)] <-"Vermont"
pov$State[grepl("Virginia.....................", pov$State)] <-"Virginia"
pov$State[grepl("Washington...............", pov$State)] <-"Washington"
pov$State[grepl("West Virginia............", pov$State)] <-"West Virginia"
pov$State[grepl("Wisconsin.................", pov$State)] <-"Wisconsin"
pov$State[grepl("Wyoming..................", pov$State)] <-"Wyoming"
pov$State[grepl("     United States…….", pov$State)] <-"United States"

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Percent without health insurance. 2018 and 2019 years included. 
#Upload
insur <- read.csv("Census_percent_no health_insur.csv")

#Rename colnames
insur <- insur %>%
  select("Table.with.row.headers.in.column.A.and.column.headers.in.rows.6.through.10", "X", "X.3", "X.5", "X.7") %>%
  rename("State" = "Table.with.row.headers.in.column.A.and.column.headers.in.rows.6.through.10") %>%
  rename("Medicaid Expand" = "X") %>%
  rename("2018 Uninsured" = "X.3") %>%
  rename("2019 Uninsured" = "X.5") %>%
  rename("Difference" = "X.7")

# Remove rows. 
insur <- insur[-c(1:10, 12, 23, 34, 45, 56, 68:79), ]

#Rename states.
insur$State <- as.character(insur$State)

insur$State[grepl("Alabama……………………………….", insur$State)] <- "Alabama"
insur$State[grepl("Alaska……………………………………..", insur$State)] <- "Alaska"
insur$State[grepl("Arizona…………………………………..", insur$State)] <- "Arizona"
insur$State[grepl("Arkansas……………………………….", insur$State)] <- "Arkansas"
insur$State[grepl("California………………………………", insur$State)] <- "California"
insur$State[grepl("Colorado……………………………….", insur$State)] <- "Colorado"
insur$State[grepl("Connecticut…………………………", insur$State)] <- "Connecticut"
insur$State[grepl("Delaware……………………………….", insur$State)] <- "Delaware"
insur$State[grepl("District of Columbia…………..", insur$State)] <- "District of Columbia"
insur$State[grepl("Florida……………………………………", insur$State)] <-"Florida"
insur$State[grepl("Georgia…………………………………", insur$State)] <-"Georgia"
insur$State[grepl("Hawaii…………………………………….", insur$State)] <-"Hawaii"
insur$State[grepl("Idaho……………………………………..", insur$State)] <-"Idaho"
insur$State[grepl("Illinois……………………………………..", insur$State)] <-"Illinois"
insur$State[grepl("Indiana…………………………………..", insur$State)] <-"Indiana"
insur$State[grepl("Iowa………………………………………..", insur$State)] <-"Iowa"
insur$State[grepl("Kansas…………………………………..", insur$State)] <-"Kansas"
insur$State[grepl("Kentucky………………………………", insur$State)] <-"Kentucky"
insur$State[grepl("Louisiana………………………………", insur$State)] <-"Louisiana"
insur$State[grepl("Maine……………………………………..", insur$State)] <-"Maine"
insur$State[grepl("Maryland………………………………", insur$State)] <-"Maryland"
insur$State[grepl("Massachusetts…………………..", insur$State)] <-"Massachusetts"
insur$State[grepl("Michigan……………………………….", insur$State)] <-"Michigan"
insur$State[grepl("Minnesota…………………………….", insur$State)] <-"Minnesota"
insur$State[grepl("Mississippi…………………………….", insur$State)] <-"Mississippi"
insur$State[grepl("Missouri…………………………………", insur$State)] <-"Missouri"
insur$State[grepl("Montana……………………………….", insur$State)] <-"Montana"
insur$State[grepl("Nebraska………………………………", insur$State)] <-"Nebraska"
insur$State[grepl("Nevada…………………………………", insur$State)] <-"Nevada"
insur$State[grepl("New Hampshire…………………..", insur$State)] <-"New Hampshire"
insur$State[grepl("New Jersey…………………………..", insur$State)] <-"New Jersey"
insur$State[grepl("New Mexico………………………….", insur$State)] <-"New Mexico"
insur$State[grepl("New York………………………………", insur$State)] <-"New York"
insur$State[grepl("North Carolina…………………….", insur$State)] <-"North Carolina"
insur$State[grepl("North Dakota……………………….", insur$State)] <-"North Dakota"
insur$State[grepl("Ohio……………………………………….", insur$State)] <-"Ohio"
insur$State[grepl("Oklahoma……………………………", insur$State)] <-"Oklahoma"
insur$State[grepl("Oregon………………………………….", insur$State)] <-"Oregon"
insur$State[grepl("Pennsylvania………………………", insur$State)] <-"Pennsylvania"
insur$State[grepl("Rhode Island……………………….", insur$State)] <-"Rhode Island"
insur$State[grepl("South Carolina……………………", insur$State)] <- "South Carolina"
insur$State[grepl("South Dakota………………………", insur$State)] <-"South Dakota"
insur$State[grepl("Tennessee…………………………..", insur$State)] <-"Tennessee"
insur$State[grepl("Texas……………………………………..", insur$State)] <-"Texas"
insur$State[grepl("Utah………………………………………..", insur$State)] <-"Utah"
insur$State[grepl("Vermont………………………………..", insur$State)] <-"Vermont"
insur$State[grepl("Virginia…………………………………..", insur$State)] <-"Virginia"
insur$State[grepl("Washington………………………….", insur$State)] <-"Washington"
insur$State[grepl("West Virginia……………………….", insur$State)] <-"West Virginia"
insur$State[grepl("Wisconsin…………………………….", insur$State)] <-"Wisconsin"
insur$State[grepl("Wyoming……………………………….", insur$State)] <-"Wyoming"
insur$State[grepl("United States…………..", insur$State)] <-"United States"


```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Average population. State population for 2018 and 2019. 
#Upload
pop <- read.csv("Census_Annual estimate of res population for US, regions, states, and P 4.2010 to 07.2019_nst-est2019-01.csv")

pop <- pop %>%
  select("table.with.row.headers.in.column.A.and.column.headers.in.rows.3.through.4...leading.dots.indicate.sub.parts.", "X.10", "X.11") %>%
  rename("State" = "table.with.row.headers.in.column.A.and.column.headers.in.rows.3.through.4...leading.dots.indicate.sub.parts.") %>%
  rename("2018 Pop" = "X.10") %>%
  rename("2019 Pop" = "X.11")

# Remove rows. 
pop <- pop[-c(1:3, 5:8, 60:66), ]


#Rename states.
pop$State <- as.character(pop$State)


pop$State[grepl(".Alabama", pop$State)] <- "Alaska"
pop$State[grepl(".Alaska", pop$State)] <- "Alaska"
pop$State[grepl(".Arizona", pop$State)] <- "Arizona"
pop$State[grepl(".Arkansas", pop$State)] <- "Arkansas"
pop$State[grepl(".California", pop$State)] <- "California"
pop$State[grepl(".Colorado", pop$State)] <- "Colorado"
pop$State[grepl(".Connecticut", pop$State)] <- "Connecticut"
pop$State[grepl(".Delaware", pop$State)] <- "Delaware"
pop$State[grepl(".District of Columbia", pop$State)] <- "District of Columbia"
pop$State[grepl(".Florida", pop$State)] <-"Florida"
pop$State[grepl(".Georgia", pop$State)] <-"Georgia"
pop$State[grepl(".Hawaii", pop$State)] <-"Hawaii"
pop$State[grepl(".Idaho", pop$State)] <-"Idaho"
pop$State[grepl(".Illinois", pop$State)] <-"Illinois"
pop$State[grepl(".Indiana", pop$State)] <-"Indiana"
pop$State[grepl(".Iowa", pop$State)] <-"Iowa"
pop$State[grepl(".Kansas", pop$State)] <-"Kansas"
pop$State[grepl(".Kentucky", pop$State)] <-"Kentucky"
pop$State[grepl(".Louisiana", pop$State)] <-"Louisiana"
pop$State[grepl(".Maine", pop$State)] <-"Maine"
pop$State[grepl(".Maryland", pop$State)] <-"Maryland"
pop$State[grepl(".Massachusetts", pop$State)] <-"Massachusetts"
pop$State[grepl(".Michigan", pop$State)] <-"Michigan"
pop$State[grepl(".Minnesota", pop$State)] <-"Minnesota"
pop$State[grepl(".Mississippi", pop$State)] <-"Mississippi"
pop$State[grepl(".Missouri", pop$State)] <-"Missouri"
pop$State[grepl(".Montana", pop$State)] <-"Montana"
pop$State[grepl(".Nebraska", pop$State)] <-"Nebraska"
pop$State[grepl(".Nevada", pop$State)] <-"Nevada"
pop$State[grepl(".New Hampshire", pop$State)] <-"New Hampshire"
pop$State[grepl(".New Jersey", pop$State)] <-"New Jersey"
pop$State[grepl(".New Mexico", pop$State)] <-"New Mexico"
pop$State[grepl(".New York", pop$State)] <-"New York"
pop$State[grepl(".North Carolina", pop$State)] <-"North Carolina"
pop$State[grepl(".North Dakota", pop$State)] <-"North Dakota"
pop$State[grepl(".Ohio", pop$State)] <-"Ohio"
pop$State[grepl(".Oklahoma", pop$State)] <-"Oklahoma"
pop$State[grepl(".Oregon", pop$State)] <-"Oregon"
pop$State[grepl(".Pennsylvania", pop$State)] <-"Pennsylvania"
pop$State[grepl(".Rhode Island", pop$State)] <-"Rhode Island"
pop$State[grepl(".South Carolina", pop$State)] <- "South Carolina"
pop$State[grepl(".South Dakota", pop$State)] <-"South Dakota"
pop$State[grepl(".Tennessee", pop$State)] <-"Tennessee"
pop$State[grepl(".Texas", pop$State)] <-"Texas"
pop$State[grepl(".Utah", pop$State)] <-"Utah"
pop$State[grepl(".Vermont", pop$State)] <-"Vermont"
pop$State[grepl(".Virginia", pop$State)] <-"Virginia"
pop$State[grepl(".Washington", pop$State)] <-"Washington"
pop$State[grepl(".West Virginia", pop$State)] <-"West Virginia"
pop$State[grepl(".Wisconsin", pop$State)] <-"Wisconsin"
pop$State[grepl(".Wyoming", pop$State)] <-"Wyoming"

```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Need to merge the datasets with all the SES varibles. 
ses <- left_join(pop, insur, by = "State")

ses2 <- left_join(ses, medinc, by ="State")

#Final SES data frame. Second dataframe corrected to "pov". "insur" was merged a second time here. 

ses3 <- left_join (ses2, pov, by = "State")

#trim whitespace in state names
ses3$State = str_trim(ses3$State, side=c("both", "left", "right"))


###Create cases and deaths sex-disaggregated dataframe
library(readxl)
coviddisagg <- read_xlsx("US Sex-Disaggregated Data_TimeSeries.xlsx")

#Reformat Date column of sex-disaggregated cases & deaths into dates
library(lubridate)
coviddisagg$Date = ymd(coviddisagg$Date)

#Remove unnecessary columns
coviddisagg <- coviddisagg %>% select(!contains("...")) 

#Remove whitespaces in state names
coviddisagg$State = str_trim(coviddisagg$State, side=c("both", "left", "right"))

#Removing NA rows
coviddisagg = coviddisagg %>% filter(!is.na(State))

#Join SES & COVID sex-disaggregated data.
# Michelle: I want to drop the "Source" column in the final dataset, and I want it to be arranged by country and date with the covariates matching. 
covidsex <- left_join(coviddisagg, ses3, by="State") %>%
  mutate(case_ratio = Male_cc/Female_cc) %>%
  mutate(death_ratio = Male_d/Female_d)


covidsex <- covidsex %>% 
  group_by(State) %>%
  arrange (Date) %>%
  mutate(new_cases_m = Male_cc - lag(Male_cc)) %>%
  mutate (new_cases_f= Female_cc - lag(Female_cc)) %>%
  mutate(new_case_ratio = new_cases_f/new_cases_m) %>%
  mutate(case_ratio = Male_cc/Female_cc) %>%
  mutate(death_ratio = Male_d/Female_d)

# Rename "US Virgin Islands" to "US Virgin Island"
covidsex$State[grepl("US Virgin Islands", covidsex$State)] <- "US Virgin Island"

```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Global Data

library(readr)

global5050 <- read_csv("global5050.csv") %>% select (Country, case_date= "Cases date", male_cases = "Cases (% male)",
                                                    female_cases = "Cases (% female)", 
                                                    deaths_mfratio = "Proportion of deaths in confirmed cases (Male:female ratio)")
                                                    
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Scatterplots of confirmed cases against covariates. 

covidsex$`Percent Pov`<-as.numeric(covidsex$`Percent Pov`)
covidsex$`Median Income` <-as.numeric(covidsex$`Median Income`)
covidsex$`2019 Uninsured` <-as.numeric(covidsex$`2019 Uninsured`)

# Percent in Poverty
A1 <- covidsex %>% filter(!is.na(case_ratio), (!is.na(`Percent Pov`))) %>%
  group_by(State) %>%
  ggplot(aes(x=`Percent Pov`, y=case_ratio)) +
  geom_point()+
  scale_y_continuous(limits = c(0.5, 3.0)) +
  scale_x_continuous(limits=c(0, 50, 10)) +
  theme_bw() +
  xlab("Percent living in poverty") +
  ylab("Ratio F:M") 
  #ggtitle("Ratio of Female to Male COVID cases against Pecent in Poverty Per State") +
  #theme(plot.title = element_text(size=12, hjust = 0.5, vjust = 2))

# Median Income
A2 <- covidsex %>% filter(!is.na(case_ratio), (!is.na(`Median Income`))) %>%
  group_by(State) %>%
  ggplot(aes(x=`Median Income`, y=case_ratio)) +
  geom_point()+
  scale_y_continuous(limits = c(0.5, 3.0)) +
  scale_x_continuous(limits=c(0, 60, 10)) +
  theme_bw() +
  xlab("Median Income") +
  ylab("Ratio F:M") 
  #ggtitle("Ratio of Female to Male COVID cases against Median Income in the US") +
  #theme(plot.title = element_text(size=12, hjust = 0.5, vjust = 2))

#Uninsured
A3 <- covidsex %>% filter(!is.na(case_ratio), (!is.na(`2019 Uninsured`))) %>%
  group_by(State) %>%
  ggplot(aes(x=`2019 Uninsured`, y=case_ratio)) +
  geom_point()+
  scale_y_continuous(limits = c(0.5, 3.0)) +
  scale_x_continuous(limits=c(0, 50, 10)) +
  theme_bw() +
  xlab("Percent without Health Insurance") +
  ylab("Ratio F:M") 
  #ggtitle("Ratio of Female to Male COVID cases against Percent without Health Insurance in the US") +
  #theme(plot.title = element_text(size=12, hjust = 0.5, vjust = 2))

library(grid)
library(gridExtra)
grid.arrange(A1, A2, A3, nrow = 3, ncol = 1, top = "Ratio of Female to Male COVID cases against covariates per State")
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
#Scatterplots of death ratio against covariates. 
#Percent in Poverty
D1 <- covidsex %>% filter(!is.na(death_ratio), (!is.na(`Percent Pov`))) %>%
  group_by(State) %>%
  ggplot(aes(x=`Percent Pov`, y=death_ratio)) +
  geom_point()+
  scale_y_continuous(limits = c(0.5, 3.0)) +
  scale_x_continuous(limits=c(0, 50, 10)) +
  theme_bw() +
  xlab("Percent living in poverty") +
  ylab("Ratio F:M") 
  #ggtitle("Ratio of Female to Male COVID deaths against Pecent in Poverty Per State") +
  #theme(plot.title = element_text(size=12, hjust = 0.5, vjust = 2))


# Median Income
D2 <- covidsex %>% filter(!is.na(death_ratio)) %>%
  group_by(State) %>%
  ggplot(aes(x=`Median Income`, y=death_ratio)) +
  geom_point()+
  scale_y_continuous(limits = c(0.5, 3.0)) +
  scale_x_continuous(limits=c(0, 60, 10)) +
  theme_bw() +
  xlab("Median Income") +
  ylab("Ratio F:M") 
  #ggtitle("Ratio of Female to Male COVID deaths against Median Income in the US") +
  #theme(plot.title = element_text(size=12, hjust = 0.5, vjust = 2))

#Uninsured
D3 <- covidsex %>% filter(!is.na(death_ratio), (!is.na(`2019 Uninsured`))) %>%
  group_by(State) %>%
  ggplot(aes(x=`2019 Uninsured`, y=death_ratio)) +
  geom_point()+
  scale_y_continuous(limits = c(0.5, 3.0)) +
  scale_x_continuous(limits=c(0, 50, 10)) +
  theme_bw() +
  xlab("Percent without Health Insurance") +
  ylab("Ratio F:M") 
  #ggtitle("Ratio of Female to Male COVID deaths against Percent without Health Insurance in the US") +
  #theme(plot.title = element_text(size=12, hjust = 0.5, vjust = 2))

grid.arrange(D1, D2, D3, nrow = 3, ncol = 1, top = "Ratio of Female to Male COVID deaths against covariates per State")

```






