---
title: ""
output: html_document
---

## What Data?

In our assessment of sex-disaggregated COVID-19 cases and deaths, we compiled data from a variety of sources including sociodemographic data, COVID-19 case and death data, insurance coverage, and sex ratios per state. For our analysis at the global level, we obtained sex-disaggregated COVID-19 summary information for any countries reporting it within the same time period. 
 
For the United States, we used weekly and cumulative data collected by the Gendersci Lab. The GenderSci Lab reports manually extracts COVID-19 related case and mortality data each week from other publicly available state public health departments. They have data available from mid-April 2020 until present, however, for this analysis the latest data is for Nov. 30, 2020. GenderSci’s data had cumulative cases, new weekly cases as well as frequency and percent of cases disaggregated by sex for confirmed cases and deaths. We collected our sociodemographic data on population, percent living in poverty, percent without health insurance, and median income per state from the U.S. [Census Bureau’s online database](https://www.census.gov/quickfacts/fact/table/US/PST045219).  
 
 
To merge and form a dataset for the United States, we had to do substantial data cleaning on data from the U.S. Census. Each dataset from the U.S. Census required cleaning to get it into the right format. We had to rename column names and rename each state so that we could join them with the other datasets. We dropped columns with data that did not have either 2018 or 2019 data for the measure we wanted or had additional information on sources, year-to-year differences, etc. We cleaned the data from GenderSci using lubridate to change the date format, remove unnecessary columns and NA rows. We also removed white spaces in state names using `str_trim`. We then merged GenderSci and U.S. Census Bureau data and created two new variables, `case_ratio` and `death_ratio` using the `mutate` function.
 
 
For our global perspective, we used data from the [Global 5050](https://globalhealth5050.org/the-sex-gender-and-covid-19-project/) which looks at sex-disaggregated COVID-19 data by country. The Global 5050 data was very clean from the start so we just selected columns with country names, case dates, male cases, female cases, and female to male death ratio. 

## US Scatterplots
As part of our exploratory analysis, we created scatterplots to plot the sex-disaggregated ratio (represented as the percent of female to male covid cases) of new, weekly COVID covid cases and deaths per state against each three sociodemographic indicators. As we’ve learned since the start of the pandemic in the US, COVID is not, as Madonna [asserted](https://www.cnn.com/2020/03/23/entertainment/madonna-coronavirus-video-intl-scli/index.html), “the Great Equalizer.” We also know that [1 in 3 jobs held by women are essential during the pandemic](https://www.nytimes.com/2020/04/18/us/coronavirus-women-essential-workers.html), which often are [low-paying jobs](https://www.theatlantic.com/ideas/archive/2020/05/why-are-americas-most-essential-workers-so-poorly-treated/611575/) with probably higher risk of exposure to COVID-19 at work compared to non-essential workers.  We hypothesized that disparate COVID outcomes among men and women may be related to three sociodemographic indicators that may make people more vulnerable to COVID. We were interested in seeing the relationship between the sex-disaggregated case and death ratios against three covariates: 1) percent living in poverty, 2) percent without insurance; and 3) median household income. The relationship can be seen below. Our visualizations show very weak to no correlation between sex-disaggregated case and death ratios and our covariates but based on emerging [research](https://www.pewsocialtrends.org/2020/09/24/economic-fallout-from-covid-19-continues-to-hit-lower-income-americans-the-hardest/), [news](https://www.nytimes.com/2020/03/15/world/europe/coronavirus-inequality.html), and our intuition, we believe that a more thorough regression analysis should be done to capture the new sex-disaggregated case or death ratios overtime and explore its relationship between income disparity and sex-disaggregated case and death ratios and our covariates.
